### ISSUE TITLE
Make KafkaJS client configuration configurable

### ISSUE THREAD

**Issue by SalvadorCali** [mia-platform/flow-manager-client#110]
## The feature or bug you are proposing
Make the entire configuration of the KafkaJS client configurable (at the moment only the following fields are configurable clientId, brokers, authMechanism, username, password, connectionTimeout, authenticationTimeout), in particular add the `retry` object: https://kafka.js.org/docs/configuration#default-retry

## The description of the bug or the rationale of your proposal
Due to the current implementation of the function that handles the consumer status and the limited number of retries (default = 5), our services that use the `flow-manager-client` go from the STOP, to the DISCONNECT and end in the CRASH event with `healthy: true`. If the reconnection fails 5 times, the service remains active but it can't process new requests (`{ healthy: true, ready: false }`) and we have to manually restart the pod.

![image](https://user-images.githubusercontent.com/37811007/189851261-5756ad16-c9cf-409b-afa6-84edba607d34.png)

![image](https://user-images.githubusercontent.com/37811007/189853048-b30637b8-fdbd-4a8a-842d-759a99497539.png)

## A snippet of code for replicating the issue or showing the proposal usage if applicable
Add the `retry` object to the `prepareConfig` function or, even better, make the entire KafkaJS configuration configurable.

```
function prepareConfig({
  clientId,
  brokers,
  authMechanism,
  username,
  password,
  connectionTimeout,
  authenticationTimeout,
  retry
}) {
  const brokersList = commaStringToList(brokers)

  const kafkaConfig = {
    clientId,
    brokers: brokersList,
    logLevel: logLevel.WARN,
    logCreator: PinoLogCreator,
    connectionTimeout,
    authenticationTimeout,
    retry
  }

  if (!username || !password) {
    return kafkaConfig
  }

  /* istanbul ignore next */
  return {
    ...kafkaConfig,
    ssl: true,
    sasl: {
      mechanism: authMechanism || 'PLAIN',
      username,
      password,
    },
  }
}
```

## The expected result for your bug
The KafkaJS client is more configurable and our services that use the `flow-manager-client` library can try to reconnect until they reach a new connection.

### Your environment
node: `v16.16.0`

custom-plugin-lib: `v5.1.1`

os: `Ubuntu 20.04.4 LTS`

**Comment by danibix95** [comment]
I would close this issue for the moment, since #119 has solved the problem related to the `retries` property.
